/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesContentCreationRouteImport } from './routes/services/content-creation'
import { Route as ServicesFunnelsAutomationRouteImport } from './routes/services/funnels-automation'
import { Route as ServicesGoogleAdsRouteImport } from './routes/services/google-ads'
import { Route as ServicesMetaAdsRouteImport } from './routes/services/meta-ads'
import { Route as ServicesSeoRouteImport } from './routes/services/seo'
import { Route as ServicesWebdesignRouteImport } from './routes/services/webdesign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesContentCreationRoute = ServicesContentCreationRouteImport.update({
  id: '/services/content-creation',
  path: '/services/content-creation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFunnelsAutomationRoute =
  ServicesFunnelsAutomationRouteImport.update({
    id: '/services/funnels-automation',
    path: '/services/funnels-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesGoogleAdsRoute = ServicesGoogleAdsRouteImport.update({
  id: '/services/google-ads',
  path: '/services/google-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMetaAdsRoute = ServicesMetaAdsRouteImport.update({
  id: '/services/meta-ads',
  path: '/services/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/services/seo',
  path: '/services/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebdesignRoute = ServicesWebdesignRouteImport.update({
  id: '/services/webdesign',
  path: '/services/webdesign',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/training': typeof TrainingRoute
  '/services/content-creation': typeof ServicesContentCreationRoute
  '/services/funnels-automation': typeof ServicesFunnelsAutomationRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/meta-ads': typeof ServicesMetaAdsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/webdesign': typeof ServicesWebdesignRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/training': typeof TrainingRoute
  '/services/content-creation': typeof ServicesContentCreationRoute
  '/services/funnels-automation': typeof ServicesFunnelsAutomationRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/meta-ads': typeof ServicesMetaAdsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/webdesign': typeof ServicesWebdesignRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/training': typeof TrainingRoute
  '/services/content-creation': typeof ServicesContentCreationRoute
  '/services/funnels-automation': typeof ServicesFunnelsAutomationRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/meta-ads': typeof ServicesMetaAdsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/webdesign': typeof ServicesWebdesignRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/training'
    | '/services/content-creation'
    | '/services/funnels-automation'
    | '/services/google-ads'
    | '/services/meta-ads'
    | '/services/seo'
    | '/services/webdesign'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/training'
    | '/services/content-creation'
    | '/services/funnels-automation'
    | '/services/google-ads'
    | '/services/meta-ads'
    | '/services/seo'
    | '/services/webdesign'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/training'
    | '/services/content-creation'
    | '/services/funnels-automation'
    | '/services/google-ads'
    | '/services/meta-ads'
    | '/services/seo'
    | '/services/webdesign'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  TrainingRoute: typeof TrainingRoute
  ServicesContentCreationRoute: typeof ServicesContentCreationRoute
  ServicesFunnelsAutomationRoute: typeof ServicesFunnelsAutomationRoute
  ServicesGoogleAdsRoute: typeof ServicesGoogleAdsRoute
  ServicesMetaAdsRoute: typeof ServicesMetaAdsRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesWebdesignRoute: typeof ServicesWebdesignRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/content-creation': {
      id: '/services/content-creation'
      path: '/services/content-creation'
      fullPath: '/services/content-creation'
      preLoaderRoute: typeof ServicesContentCreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/funnels-automation': {
      id: '/services/funnels-automation'
      path: '/services/funnels-automation'
      fullPath: '/services/funnels-automation'
      preLoaderRoute: typeof ServicesFunnelsAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/google-ads': {
      id: '/services/google-ads'
      path: '/services/google-ads'
      fullPath: '/services/google-ads'
      preLoaderRoute: typeof ServicesGoogleAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/meta-ads': {
      id: '/services/meta-ads'
      path: '/services/meta-ads'
      fullPath: '/services/meta-ads'
      preLoaderRoute: typeof ServicesMetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/services/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/webdesign': {
      id: '/services/webdesign'
      path: '/services/webdesign'
      fullPath: '/services/webdesign'
      preLoaderRoute: typeof ServicesWebdesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  TrainingRoute: TrainingRoute,
  ServicesContentCreationRoute: ServicesContentCreationRoute,
  ServicesFunnelsAutomationRoute: ServicesFunnelsAutomationRoute,
  ServicesGoogleAdsRoute: ServicesGoogleAdsRoute,
  ServicesMetaAdsRoute: ServicesMetaAdsRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesWebdesignRoute: ServicesWebdesignRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
